/** 阶段2 Mock 数据：前端交互先行，阶段3 接真实 API 后替换。 */
import { Invoice } from './types';

export const MOCK_INVOICES: Invoice[] = [
  {
    id: '1',
    invoice_code: '011001900111',
    invoice_number: '12345678',
    issue_date: '2026-05-12',
    invoice_type: '专票',
    seller_name: '阿里云计算有限公司',
    buyer_name: '张三',
    total_amount: '1280.00',
    category: '数字服务',
    tags: ['云服务'],
    reimbursement_status: 'unreimbursed',
    source: 'manual',
    status: 'verified',
  },
  {
    id: '2',
    invoice_code: null,
    invoice_number: '24417000000087654321',
    issue_date: '2026-05-18',
    invoice_type: '全电',
    seller_name: '滴滴出行科技有限公司',
    buyer_name: '张三',
    total_amount: '86.50',
    category: '差旅出行',
    tags: ['打车'],
    reimbursement_status: 'unreimbursed',
    source: 'email_auto',
    status: 'verified',
  },
  {
    id: '3',
    invoice_code: '033001800122',
    invoice_number: '88991234',
    issue_date: '2026-05-20',
    invoice_type: '普票',
    seller_name: '中国铁路 12306',
    buyer_name: '张三',
    total_amount: '553.00',
    category: '差旅出行',
    tags: ['高铁'],
    reimbursement_status: 'submitted',
    source: 'email_auto',
    status: 'verified',
  },
  {
    id: '4',
    invoice_code: null,
    invoice_number: '24417000000011112222',
    issue_date: '2026-05-22',
    invoice_type: '全电',
    seller_name: '海底捞餐饮股份有限公司',
    buyer_name: '张三',
    total_amount: '328.00',
    category: '日常餐饮',
    tags: ['聚餐'],
    reimbursement_status: 'reimbursed',
    source: 'manual',
    status: 'verified',
  },
  {
    id: '5',
    invoice_code: '044001700133',
    invoice_number: '55667788',
    issue_date: '2026-05-25',
    invoice_type: '专票',
    seller_name: 'Shimano (Singapore) Pte',
    buyer_name: '张三',
    total_amount: '2150.00',
    category: '运动爱好',
    tags: ['骑行', '装备'],
    reimbursement_status: 'unreimbursed',
    source: 'manual',
    status: 'pending',
  },
  {
    id: '6',
    invoice_code: null,
    invoice_number: '24417000000033334444',
    issue_date: '2026-05-28',
    invoice_type: '全电',
    seller_name: '亚马逊云科技',
    buyer_name: '张三',
    total_amount: '1890.00',
    category: '数字服务',
    tags: ['AWS'],
    reimbursement_status: 'submitted',
    source: 'email_auto',
    status: 'verified',
  },
  {
    id: '7',
    invoice_code: null,
    invoice_number: null,
    issue_date: null,
    invoice_type: null,
    seller_name: null,
    buyer_name: null,
    total_amount: null,
    category: null,
    tags: null,
    reimbursement_status: 'unreimbursed',
    source: 'manual',
    status: 'processing',
  },
  {
    id: '8',
    invoice_code: '055001600144',
    invoice_number: '99001122',
    issue_date: '2026-06-01',
    invoice_type: '打车票',
    seller_name: '北京出租汽车',
    buyer_name: '张三',
    total_amount: '42.00',
    category: '差旅出行',
    tags: ['出租车'],
    reimbursement_status: 'reimbursed',
    source: 'manual',
    status: 'verified',
  },
];

export const MOCK_STATS = {
  total: 8649.5,
  unreimbursed: 5508.5,
  maxSingle: 2150.0,
};

export const MOCK_CATEGORY = [
  { name: '数字服务', 金额: 3170 },
  { name: '差旅出行', 金额: 1481.5 },
  { name: '运动爱好', 金额: 2150 },
  { name: '日常餐饮', 金额: 328 },
];

export const MOCK_TREND = [
  { month: '1月', 金额: 1200 },
  { month: '2月', 金额: 980 },
  { month: '3月', 金额: 1650 },
  { month: '4月', 金额: 1320 },
  { month: '5月', 金额: 4787.5 },
  { month: '6月', 金额: 42 },
];
